# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:

# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  
steps:
- task: CmdLine@2
  inputs:
    script: |
      echo start build
      cmd /C build.cmd
      cmd copy rawout/* ..
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'rawout'
    artifact: 'rawout'
    publishLocation: 'pipeline'
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github lxldoc'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    title: '构建'
    releaseNotesSource: 'inline'
    releaseNotesInline: '构建'
    assets: 'rawout/*'
    isDraft: false
    isPreRelease: false
    addChangeLog: true
